A few updates to the start-stop script.
The script was using `ps -p` to test if a process is running. The `-p`
option is not available on all implementations of `ps` (e.g.:
busybox). Instead, use `kill -0`, which is more portable to verify if a
PID is running.

Reformat the code to use 2 spaces instead of a mix of 2 and 4 (2 was
dominant in the script, so I stick to that instead of 4).

Replace backticks with subshell, which is also more portable.

Fix a test in the script to start the server (checking if the jar file
exists).

RB_ID=816412

diff --git a/bookkeeper-server/bin/bookkeeper b/bookkeeper-server/bin/bookkeeper
--- a/bookkeeper-server/bin/bookkeeper
+++ b/bookkeeper-server/bin/bookkeeper
@@ -84,11 +84,13 @@ if [ -z "${BUILT_JAR}" ] && [ -z "${BOOKIE_JAR}" ]; then
     fi
 fi
 
-if [ -e "$BUILT_JAR" ]; then
-    BOOKIE_JAR=$BUILT_JAR
-else
-    echo "Could not find bookkeeper jar."
-    exit 1
+if [ -e "${BUILT_JAR}" ]; then
+  BOOKIE_JAR="${BUILT_JAR}"
+fi
+
+if [ ! -e "${BOOKIE_JAR}" ]; then
+  echo "Could not find bookkeeper jar."
+  exit 1
 fi
 
 bookkeeper_help() {
